[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

# if you choose `ruff` itself
[language-server.ruff]
command = "ruff"
args = ["server"]
