[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = ["pyrightconfig.json"]
comment-token = "#"
language-servers = ["basedpyright", "ruff"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=88"
]

[language-server.basedpyright]
args = ["--stdio","--verbose"]
command = "basedpyright-langserver"

[language-server.basedpyright.analysis]
stubPath = "/apps/auth"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config]
settings = {args = []}

[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }
language-servers = ["vscode-html-language-server", "emmet-ls", "tailwindcss-ls"]

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "scss"
formatter = { command = 'npx', args = ["prettier", "--parser", "scss"] }

[[language]]
name = "javascript"
language-servers = [{except-features = ["format"], name = "typescript-language-server"}, "biome"]
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [{except-features = ["format"], name = "typescript-language-server"}, "biome"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [{except-features = ["format"], name = "typescript-language-server"}, "emmet-ls", "tailwindcss-ls", "biome"]
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [{except-features = ["format"], name = "typescript-language-server"}, "emmet-ls", "tailwindcss-ls", "biome"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
# formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "markdown"
formatter = { command = 'npx', args = ["prettier", "--parser", "markdown"] }
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
